music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
restore_paused "yes"
bind_to_address "127.0.0.1"
port "6601"
auto_update "yes"
state_file "~/.config/mpd/state"

audio_output {
    type "alsa"
    name "ALSA Default"
    device "default"
    mixer_type "software"
}

audio_output {
    type    "fifo"
    name    "my_fifo"
    path    "/tmp/mpd.fifo"
    format  "44100:16:2"
}
