monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_00_1b.0"
      }
    ]
    actions = {
      update-props = {
        api.acp.auto-port = false
        api.acp.auto-profile = false
      }
    }
  }
]
