"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
${custom.git_branch}\
${custom.git_status}\
${custom.jj}\
$c\
$rust\
$golang\
$lua\
$ocaml\
$zig\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

# right_format = """
# $python\
# $nodejs\
# $golang\
# $rust\
# $c\
# $cmd_duration\
# ${custom.git_status}\
# ${custom.git_branch}\
# ${custom.git_state}\
# ${custom.jj}\
# $hostname\
# $username\
# """

[custom.jj]
command = "jj-starship prompt --no-jj-prefix"
when = 'jj root >/dev/null 2>&1'
format = "$output "

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[os]
disabled = false
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"
Mint = "󰣭"
Macos = "󰀵"
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Artix = "󰣇"
Debian = "󰣚"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"dev" = "󰲋 "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(* $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind $stashed)]($style)"
style = "cyan"
conflicted = "$count= "
untracked = "$count? "
modified = "$count! "
staged = "$count+ "
renamed = "$count» "
deleted = "$count✘ "
stashed = "$count≡ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[custom.git_branch]
format = "$output"
command = "starship module git_branch"
when = "! jj --ignore-working-copy root"
require_repo = true

[custom.git_status]
format = "$output"
command = "starship module git_status"
when = "! jj --ignore-working-copy root"
require_repo = true

[custom.git_state]
format = "$output"
command = "starship module git_state"
when = "! jj --ignore-working-copy root"
require_repo = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nodejs]
symbol = ""
style = "green"
format = '[$symbol( $version)]($style) '

[c]
symbol = ""
style = "blue"
format = '[ $symbol( $version )]($style) '

[rust]
symbol = ""
style = "red"
format = '[$symbol( $version )]($style) '

[lua]
symbol = "󰢱"
style = "cyan"
format = '[$symbol( $version )]($style) '

[ocaml]
symbol = ""
style = "red"
format = '[$symbol( $version )]($style) '

[typst]
symbol = "󰬛"
style = "blue"
format = '[$symbol( $version )]($style) '

[golang]
symbol = ""
style = "blue"
format = '[$symbol( $version )]($style) '

[zig]
symbol = ""
style = "yellow"
format = '[$symbol( $version )]($style) '

[python]
symbol = ""
style = "yellow"
format = '[$symbol( $version)(\(#$virtualenv\)) ]($style)'
detect_extensions = []
detect_files = []
