[general]
import = ["/home/xdagiz/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
TERM = "alacritty"

[font]
size = 7
bold = { family = "Geist Mono", style = "Bold" }
italic = { family = "Geist Mono", style = "Italic" }
normal = { family = "Geist Mono", style = "Normal" }

[keyboard]
bindings = [
  { action = "Paste", key = "Insert", mods = "Shift" },
  { action = "Copy", key = "Insert", mods = "Control" },
  { action = "Copy", key = "c", mods = "Control|Shift" },
  { action = "Paste", key = "v", mods = "Control|Shift" },
  { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
  { chars = "\u001B[13;5u", key = "Return", mods = "Control" },
  { action = "SpawnNewInstance", key = "N", mods = "Control|Shift" },
]

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/usr/bin/tmux"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0
padding = { x = 16, y = 16 }
